### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by kishankarun**
Fixed the puepy pypi link

### CODE REVIEW

**Comment by kishankarun** [comment]
Hi @kkinder ,

I would like to propose to add few more steps to

> A simple first project (with no web server) would be:
> 
> ```
> index.html (index.html file)
> pyscript.json (pyscript config file)
> hello.py (Hello World code)
> puepy-0.3.6-py3-none-any.whl (PuePy wheel file)
> ```

It is mentioned that the simple first project with no web server.

It would be good if you could provide them with a github page with a sample or what should be the contents of these files :)

I got this in the browser when I tried locally
```
Loading...
(PY0001): Polyscript: Access to local files
        (using [[fetch]] configurations in &lt;py-config&gt;)
        is not available when directly opening a HTML file;
        you must use a webserver to serve the additional files.
        See <a style="text-decoration: underline;" href="https://github.com/pyscript/pyscript/issues/257#issuecomment-1119595062">this reference</a>
        on starting a simple webserver with Python.
            
```
As a first time user, I expected to make these files manually and open the index.html to see some "magic" 😜 

When I tried to create a simple html file with "Hello world", Created a simple hello.py (which prints "hello world"), and downloaded the puepy-0.3.6-py3-none-any.whl (PuePy wheel file), and I opened the index.html, 
(I didn't know where to get the pyscript.json)

I was surprised to see that it literally 'didn't work'. Also I was wondering what I should expect here. (May be an expected output screenshot would have been great)?

Could the documentation for this page be made more intuitive?

I was thinking as this is the first page, and for any beginner, if content in the page "installation" had the straightforward steps to get a basic project kickstarted, it would be great ?

**Comment by kishankarun** [comment]
For a quick start,

I modified your serve.py as below

```
import argparse
import os
import pathlib
import sys
from http import server

project_path = pathlib.Path(__file__).parent

sys.path.append(str(project_path))


class Handler(server.SimpleHTTPRequestHandler):
    def do_GET(self):
        path = self.path.split("?")[0]

        return super().do_GET()

    def end_headers(self):
        """
        Cache nothing!
        """
        self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")
        super().end_headers()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A simple HTTP server to serve examples of PuePy")
    parser.add_argument("--host", default="", help="The host on which the server runs")
    parser.add_argument("--port", type=int, default=8000, help="The port on which the server listens")
    args = parser.parse_args()

    os.chdir(project_path)
    httpd = server.HTTPServer((args.host, args.port), Handler)
    print(f"Serving at port {args.host or '*'}:{args.port}")
    httpd.serve_forever()
```

Had a hello_world.py

```
from puepy import Application, Page, t

app = Application()


@app.page()
class HelloWorldPage(Page):
    def populate(self):
        t.h1("Hello, World!")


app.mount("#app")
```

And index.html

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PuePy Hello, World</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://pyscript.net/releases/2024.7.1/core.css">
  <script type="module" src="https://pyscript.net/releases/2024.7.1/core.js"></script>
</head>
<body>
<div id="app">Loading...</div>
<script type="mpy" src="./hello_world.py" config="./pyscript.json"></script>
</body>
</html>
```

And pyscript.json as 

```
{
  "name": "PuePy Tutorial",
  "debug": true,
  "files": {},
  "js_modules": {
    "main": {
      "https://cdn.jsdelivr.net/npm/morphdom@2.7.2/+esm": "morphdom"
    }
  },
  "packages": [
    "./puepy-0.3.6-py3-none-any.whl"
  ]
}
```

And the `.whl` file `puepy-0.3.6-py3-none-any.whl` was included from pypi as per documentation

Started the local server with

```
python serve.py
```

which started the server by default in port 8000

And the browser showed

### Hello, World!

as expected

The list of files 

```
hello_world.py
index.html
puepy-0.3.6-py3-none-any.whl
pyscript.json
serve.py
```

**Comment by kkinder** [comment]
Hmm, good point. You do actually need to serve the files over http, not file:, for the whole stack to work as expected. I had in mind though, if you're learning, the best place to do that is probably on pyscript.com, where you get an editor, a web server, etc. The examples are all already there, and you can clone the project on pyscript and edit it from there. Was it not clear that you could use pyscript.com or why did you decide not to?

**Comment by kishankarun** [comment]
> Hmm, good point. You do actually need to serve the files over http, not file:, for the whole stack to work as expected. I had in mind though, if you're learning, the best place to do that is probably on pyscript.com, where you get an editor, a web server, etc. The examples are all already there, and you can clone the project on pyscript and edit it from there. Was it not clear that you could use pyscript.com or why did you decide not to?

You are right, the examples are there, but the installation page I thought could have been something like the fastapi installation page 😊

https://fastapi.tiangolo.com/#installation

When I got to the project the first time, I had navigated to the pyscipt.com editor and found the project files 👍 

But when I was thinking of an absolute beginner (who has a background in python, and a bit of web), for him to get kickstarted with puepy, I thought the page could have been made better.

Later on, when I moved to the tutorial page https://docs.puepy.dev/tutorial/00-using-this-tutorial/ it is clear that it is to be used in pyscript.com and that it can be directly used by cloning the repo and running serve_examples.py 😊

So would it be better, if the installation page contents and using-this-tutorial be merged to make it more clear?

**Pull request merged**
